# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 18:31
from __future__ import unicode_literals

import WorkoutBuddy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='MM-DD-YYYY')),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, help_text='Weight in lbs or kgs', max_digits=3)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
                ('chest_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter chest size', max_digits=3)),
                ('back_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter back size', max_digits=3)),
                ('arm_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter arm size', max_digits=3)),
                ('forearm_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter forearm size', max_digits=3)),
                ('waist_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter waist size', max_digits=3)),
                ('quad_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter quad size', max_digits=3)),
                ('calf_size', models.DecimalField(decimal_places=1, default=0.0, help_text='Enter calf size', max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomExerciseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_image', models.ImageField(upload_to=WorkoutBuddy.models.user_directory_exercise_image_path)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.CustomExercise')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_description', models.TextField(max_length=2000)),
                ('exercise_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MainWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_workout_name', models.CharField(help_text='Enter a name for your MainWorkout', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaxBench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bench', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MaxDeadLift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_dead_lift', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MaxSquat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_squat', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=WorkoutBuddy.models.user_directory_profile_image)),
                ('custom_exercises', models.ManyToManyField(to='WorkoutBuddy.CustomExercise')),
                ('custom_main_workouts', models.ManyToManyField(to='WorkoutBuddy.MainWorkout')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to=WorkoutBuddy.models.user_directory_profile_image)),
                ('date', models.DateField(help_text='MM-DD-YYYY')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=WorkoutBuddy.models.user_directory_profile_image)),
                ('date_time', models.DateTimeField(help_text='MM-DD-YYYY HH:MM:SS')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], default=1)),
                ('reps', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SubWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_workout_name', models.CharField(help_text='Enter a name for your SubWorkout', max_length=100)),
                ('date', models.DateField(help_text='Enter a Date')),
                ('custom_exercises', models.ManyToManyField(to='WorkoutBuddy.CustomExercise')),
                ('default_exercises', models.ManyToManyField(to='WorkoutBuddy.DefaultExercise')),
                ('main_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.MainWorkout')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='MM-DD-YYYY')),
                ('total_sets', models.IntegerField(default=0)),
                ('total_reps', models.IntegerField(default=0)),
                ('total_weight', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], default=1)),
                ('rep_range', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kilograms'), ('lbs', 'pounds')], default='lbs', max_length=3)),
                ('completed_sets', models.ManyToManyField(to='WorkoutBuddy.Set')),
                ('workout_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='completed_exercises',
            field=models.ManyToManyField(to='WorkoutBuddy.WorkoutExercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile'),
        ),
        migrations.AddField(
            model_name='set',
            name='workout_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.WorkoutExercise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_sub_workouts',
            field=models.ManyToManyField(to='WorkoutBuddy.SubWorkout'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_bench',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.MaxBench'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_dead_lift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.MaxDeadLift'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_squat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.MaxSquat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='progress_photos',
            field=models.ManyToManyField(to='WorkoutBuddy.ProgressPhoto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='workout_stats',
            field=models.ManyToManyField(to='WorkoutBuddy.Workout'),
        ),
        migrations.AddField(
            model_name='mainworkout',
            name='sub_workouts',
            field=models.ManyToManyField(to='WorkoutBuddy.SubWorkout'),
        ),
        migrations.AddField(
            model_name='mainworkout',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile'),
        ),
        migrations.AddField(
            model_name='body',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile'),
        ),
    ]
