# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 23:14
from __future__ import unicode_literals

import WorkoutBuddy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutBuddy', '0004_auto_20171009_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexerciseimage',
            name='local_exercise_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='local_profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='local_profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='local_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customexerciseimage',
            name='exercise_image',
            field=models.ImageField(null=True, upload_to=WorkoutBuddy.models.user_directory_exercise_image_path),
        ),
        migrations.AlterField(
            model_name='defaultexercise',
            name='exercise_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=WorkoutBuddy.models.user_directory_profile_image),
        ),
    ]
