# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutBuddy', '0005_auto_20171021_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisegoals',
            name='sub_workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.SubWorkout'),
        ),
    ]
