# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutBuddy', '0006_exercisegoals_sub_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressphoto',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutBuddy.Profile'),
        ),
    ]
