# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 03:01
from __future__ import unicode_literals

import WorkoutBuddy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutBuddy', '0008_auto_20171028_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customexerciseimage',
            name='exercise',
        ),
        migrations.AddField(
            model_name='customexercise',
            name='exercise_image',
            field=models.ImageField(max_length=500, null=True, upload_to=WorkoutBuddy.models.user_directory_exercise_image_path),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='local_exercise_image',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CustomExerciseImage',
        ),
    ]
