# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBBackend', '0011_auto_20171105_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressphoto',
            name='local_photo',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
