# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WBBackend', '0012_auto_20171113_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='subworkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WBBackend.SubWorkout'),
        ),
    ]
