# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBBackend', '0013_workout_subworkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='subworkout',
        ),
        migrations.AddField(
            model_name='workout',
            name='subworkout_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
